CONTACT_PREFIX = "contact:"
PAID_PREFIX = "paid:"
VIEW_PREFIX = "view:"
ADMIN_PREFIX = "admin:"
DUPLICATE_PREFIX = "dup:"
PLAN_PREFIX = "plan:"
PAYMENT_METHOD_PREFIX = "paymethod:"
PAYMENT_NAV_PREFIX = "paynav:"
